# curl -X 'POST'
#  'http://localhost:3001/api/v1/login'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "user": "admin",
#  "password": "pwd"
#}'
POST http://localhost:3001/api/v1/login
accept: application/json
Content-Type: application/json

{
  "user": "admin",
  "password": "pwd"
}
bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzE4ODIxMDEsImlhdCI6MTYzMTc5NTcwMSwiaXNzIjoieW5oU0JBVlpIZ2FDYm9adnJiOFNzOSIsInN1YiI6ImFjY2VzcyJ9.OSqyaClTr6R6RN5X2nsKcgSxos-IrwEEo7o5Wl64cMBqF0r70oGEbJFGR78SFhpcT3mrX4uebfmEUD_ZNC6rCw
###

